'use strict'

/* global describe it beforeEach afterEach */
const fs = require('fs')
const path = require('path')
const chai = require('chai')
const sinon = require('sinon')
const Serverless = require('serverless')
const ServerlessSharedApiGateway = require('../src')
const AWS = require('aws-sdk-mock')

const assert = chai.assert
const serverlessFolder = path.join(__dirname, '.serverless')

describe('index.js', () => {
  let sandbox
  let serverless

  beforeEach(async () => {
    sandbox = sinon.sandbox.create()
    AWS.mock('APIGateway', 'getRestApis', {items: []})
    AWS.mock('APIGateway', 'createRestApi', (params, cb) => {
      cb(null, {
        id: 'abcdef12gh',
        name: 'test',
        description: 'Generated by the shared Serverless - AWS Api Gateway plugin',
        createdDate: '2018-01-01T00:00:00.000Z',
        apiKeySource: 'HEADER',
        endpointConfiguration: {types: ['EDGE']}
      })
    })
    AWS.mock('APIGateway', 'getResources', {
      items: [{id: 'abcde1fghi', path: '/'}]
    })

    serverless = new Serverless({servicePath: __dirname})
    await serverless.init()
    serverless.pluginManager.addPlugin(ServerlessSharedApiGateway)
  })

  afterEach((done) => {
    AWS.restore('APIGateway')
    sandbox.restore()
    done()
  })

  describe('when export command is ran', () => {
    beforeEach(() => {
      serverless.processedInput = {
        commands: ['package'],
        options: {stage: undefined, region: undefined}
      }
      return serverless.run()
    })

    it('should create a serverless.json', () => {
      assert.isTrue(fs.existsSync(`${serverlessFolder}/cloudformation-template-update-stack.json`))
      // const serverlessYaml = require(`${serverlessFolder}/serverless.json`);
      //
      // assert.equal(serverlessYaml.serviceObject.name, 'panda');
      // assert.equal(serverlessYaml.provider.environment.NODE_ENV, 'dev');
      // assert.equal(serverlessYaml.provider.environment.SERVICE_NAME, 'panda');
      //
      // assert.equal(serverlessYaml.functions.create.environment.NODE_ENV, 'test');
    })
  })
})