'use strict'

const AWS = require('aws-sdk')

class ServerlessSharedapiGateway {
  constructor (serverless, options) {
    this.serverless = serverless
    this.options = options

    // Indicate if variables are initialized to avoid run multiples init
    this.initialized = false
    this.restApiId = null
    this.restApiName = null
    this.restApiResourceId = null

    this.commands = {
      shared_api_gateway: {
        validate: {
          usage: 'Checks to see if the AWS API gateway exists and if you have permission',
          lifecycleEvents: [
            'validate'
          ]
        },
        create: {
          usage: 'Creates an AWS API gateway',
          lifecycleEvents: [
            'initialize',
            'create'
          ]
        },
        delete: {
          usage: 'Deletes an AWS API gateway',
          lifecycleEvents: [
            'initialize',
            'delete'
          ]
        }
      }
    }

    this.hooks = {
      'shared_api_gateway:delete:delete': this.deleteRestApi.bind(this),
      'shared_api_gateway:create:create': this.createRestApi.bind(this),
      'after:package:compileEvents': this.compileEvents.bind(this)
    }
  }

  _initializeVariables () {
    if (!this.initialized) {
      // Sets the credentials for AWS resources.
      const awsCreds = this.serverless.providers.aws.getCredentials()
      AWS.config.update(awsCreds)
      this.apiGateway = new AWS.APIGateway()

      this.initialized = true
    }
  }

  createRestApi () {
    this._initializeVariables()

    return this.apiGateway.createRestApi({
      name: this.restApiName,
      // binaryMediaTypes: [],
      description: 'Generated by the shared Serverless - AWS Api Gateway plugin',
      endpointConfiguration: {
        types: [
          'EDGE'
        ]
      }
    }).promise()
  }

  deleteRestApi () {
    this._initializeVariables()

    return null
  }

  _sourceArnReplaceRestApi (arr) {
    return arr.map(item => {
      if (Array.isArray(item)) return this._sourceArnReplaceRestApi(item)
      if (item && item.Ref && item.Ref === this.apiGatewayRestApiLogicalId) return this.restApiId
      else if (item && item['Fn::GetAtt']) return this.restApiResourceId
      return item
    })
  }

  _processCloudFormation () {
    this.apiGatewayRestApiLogicalId = this.serverless.pluginManager.plugins.find(plugin => plugin.apiGatewayRestApiLogicalId).apiGatewayRestApiLogicalId

    // Set restApiId on provider
    this.serverless.service.provider.apiGatewayRestApiId = this.restApiId

    // Set restApiResourceId on provider
    this.serverless.service.provider.restApiResourceId = this.restApiResourceId

    let ccfTemplate = this.serverless.service.provider.compiledCloudFormationTemplate
    let Resources = ccfTemplate.Resources

    // Remove ApiGatewayRestApi
    if (Resources.ApiGatewayRestApi) delete Resources.ApiGatewayRestApi

    const resourceKeys = Object.keys(Resources)
    resourceKeys.forEach(key => {
      if (/^ApiGateway(Resource|Method|Deployment)/.test(key)) {
        let Properties = Resources[key].Properties
        // Set restApiId on each Resource, Method, & Deployment
        if (Properties && Properties.RestApiId && Properties.RestApiId.Ref && Properties.RestApiId.Ref === this.apiGatewayRestApiLogicalId) Properties.RestApiId = this.restApiId
        // Set restApiResourceId as ParentId
        if (Properties && Properties.ParentId && Properties.ParentId['Fn::GetAtt']) Properties.ParentId = this.restApiResourceId
      } else if (/^(RegisterLambdaPermissionApiGateway|GetLambdaPermissionApiGateway)/.test(key)) {
        Resources[key].Properties.SourceArn['Fn::Join'] = this._sourceArnReplaceRestApi(Resources[key].Properties.SourceArn['Fn::Join'])
      }
    })

    // Set restApiId on Outputs
    ccfTemplate.Outputs.ServiceEndpoint.Value['Fn::Join'] = this._sourceArnReplaceRestApi(ccfTemplate.Outputs.ServiceEndpoint.Value['Fn::Join'])
  }

  compileEvents () {
    this.restApiId = this.serverless.service.provider.apiGatewayRestApiId
    this.restApiName = this.serverless.service.provider.apiGatewayRestApiName
    this.restApiResourceId = this.serverless.service.provider.apiGatewayRestApiResourceId

    if (!this.restApiId && !this.restApiName) throw new Error(`Unable to continue please provide an apiId or apiName`)

    return this.findRestApi()
      .then(() => this.findResourceId())
      .then(() => this._processCloudFormation())
  }

  _findMatchingRestApi (api) {
    if (this.restApiId) return api.id === this.restApiId
    else if (this.restApiName) return api.name === this.restApiName
    return false
  }

  findRestApi () {
    this._initializeVariables()

    const getRestApis = this.apiGateway.getRestApis({}).promise()
    return getRestApis.then((data) => {
      if (this.restApiName) {
        let matchingRestApis = data.items.filter(api => this._findMatchingRestApi(api))
        if (matchingRestApis && matchingRestApis.length > 1) throw new Error(`Found multiple APIs with the name: ${this.restApiName}. Please rename your api or specify an apiGatewayRestApiId`)
      }

      let matchingRestApi = data.items.find(api => this._findMatchingRestApi(api))
      if (this.restApiName && !matchingRestApi) {
        console.log('Unable to find a matching API Gateway attempting to create one.')

        return this.createRestApi()
      }
      return matchingRestApi
    }).then(restApi => {
      this.restApiId = restApi.id
      this.restApiName = restApi.name
    })
  }

  _findMatchingResource (resource) {
    if (this.restApiResourceId) return resource.id === this.restApiResourceId
    else return resource.path === '/'
  }

  findResourceId () {
    this._initializeVariables()

    if (!this.restApiId) throw new Error(`You must have a restApiId. Did you forget to run findRestApi?`)

    const getResources = this.apiGateway.getResources({restApiId: this.restApiId}).promise()

    return getResources.then(data => {
      let matchingResource = data.items.find(resource => this._findMatchingResource(resource))
      if (!matchingResource) console.log('Unable to find a matching API Gateway resource. Please check the id and try again.')

      return matchingResource
    }).then(resource => {
      this.restApiResourceId = resource.id
    })
  }
}

module.exports = ServerlessSharedapiGateway
